### ISSUE TITLE
[BackEnd] Implement shuffle data and show the results.

### ISSUE THREAD

**Issue by omarisai** [SeminarioIA/SimpleANNPlayground#70]

**Comment by WilfridoCO** [comment]
I've made the Shuffle-Function, can you check it? 
There was a bug during reloading the csv, it occurred due to "_typeRow.Cells" weren't cleaned before, I added the "Clear()" call.

**Comment by omarisai** [comment]
> I've made the Shuffle-Function, can you check it? There was a bug during reloading the csv, it occurred due to "_typeRow.Cells" weren't cleaned before, I added the "Clear()" call.

Good catch, I will to test in a moment.
